# Set up
```{r}
rm(list =ls())
library(tidyverse)
library(dm)
library(data.table)
library(mice)
```


# Load data
```{r}
load("D:/R/data analysis/Institutional research/technical-exercise/content/docs/data_230213_2316.Rdata")
```

# Add succss variables to evaluate student success
+ C or better is Y, otherwise is N
+ a factorial variable

```{r include=FALSE}
course_enrollments <- course_enrollments %>%
 mutate(success = case_when(
   official_grade %in% c("A","A-","B+","B","B-","C") ~ "Y",
   TRUE ~ "N")) 
course_enrollments$success <- as.factor(course_enrollments$success)
```


```{r}
mydf <- df %>%
 mutate(success = case_when(
   official_grade %in% c("A","A-","B+","B","B-","C") ~ "Y",
   TRUE ~ "N"))
```

# Convert characterial variables
+ 
```{r}
str(mydf)
cols_factor <- c("acad_plan","semester","subject","acad_career","degree","college","acad_plan_type","eff_status","success")
mydf <- as.data.table(mydf)
mydf[,c(cols_factor) := lapply(.SD,as.factor), .SDcols = cols_factor]
str(mydf)
```

# Deal with extreme cases
```{r}
student_details <- student_details %>%
  mutate(
    hs_gpa_entry = case_when(
      hs_gpa_entry <= 5 ~hs_gpa_entry, 
      TRUE ~ NA
    )
  )
```


# Imputate some variables
```{r}
vars <- c("student_id_number",
          "term_code",
          "class_nbr",
          "acad_plan",
          "hours_carried",
          "ACT_score",
          "hs_gpa_entry",
          "hardship_score",
          "instructor_id_number",
          "subject",
          "dept_code",
          "acad_career",
          "degree",
          "college",
          "acad_plan_type",
          "eff_status",
          "success")
DF <- mydf[,..vars]
```


# Save data
```{r}
dt <- format(Sys.time(),"%y%m%d_%H%M")
fileName <- paste0("data_", dt, ".Rdata",sep="")
fileName <- "data_230214_1659.Rdata"
save.image(fileName)
```

