# Summary

Through analyzing data sets, I have the following thoughts on Physics, Biology (Human Anatomy), and Spanish academic plans: 

1.  While statistical tests do not result in significant difference on student success between those three academic plans and others, they do have slightly lower success rates based on the data. 

2.  According to the data sets, those departments can consider two aspects for improving student success: 

    -   Students' perspectives 

        -   Interestingly, ACT scores are negatively associated with success rates. Considering current trend of test-optional admissions, those three departments can review their admission requirements and reconsider the importance of ACT or SAT.

                <a href="https://www.insidehighered.com/blogs/higher-ed-policy/sat-and-act-are-less-important-you-might-think" title="The SAT and ACT Are Less Important Than You Might Think">Link text</a>

            Departments may need more data to analyze standardized tests and make decisions. 

        -   Hardship scores are also negatively associated with success rates. Therefore, those departments might consider financial support for students. 

    -   Instructors' perspectives 

        -   While those data sets do not prove that teaching frequently can improve instructors' performance, the visualization of box plot does show that teaching more than five terms leads to a slight decrease in success rates. 

        -   Moreover, regression models indicate that the number of courses instructors teach is negatively associated with performance. 

        -   To improve students' success, those departments might want to review instructors' teaching loads. Since those classes are entry-level courses, considering costs of hiring instructors, they could recruit more graduate students as teaching assistants, or recruit more adjunct professors and instructors. 

 
